# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_arpa_inet
    test_fault_wrappers_ifaddrs
    test_fault_wrappers_net_ethernet
    test_fault_wrappers_net_if
    test_fault_wrappers_netdb
    test_fault_wrappers_sys_socket
)
